<a href="https://colab.research.google.com/github/sahilgoyal7214/Statistics-for-Data-Science/blob/main/Tutorial%205/Tutorial_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Question 1: Create a custom 2 x 3 array in Python and print its shape. 
import numpy as np 
x=np.array([[1,2,3], [4,5,6]]) #order 2*3: 2 rows and 3 columns 
print(x) 
print(x.shape) #shape-print the size of rows and columns 


[[1 2 3]
 [4 5 6]]
(2, 3)


In [ ]:
# Question 2: Create a random 10 x 1 array in Python and determine the mean and variance import numpy as np 
from numpy import random 
y=random.randint(11,size=(10,1)) #random 10*1 array 
print(y) 
print("The mean of the elements of the row", np.mean(y,axis=1))#mean of rows 
print("The mean of the elements of the column", np.mean(y,axis=0)) #mean of columns 
print("The variance of the elements of the row", np.var(y,axis=1)) #variance of rows 
print("The variance of the elements of the column", np.var(y,axis=0)) #variance of column 


[[ 6]
 [ 0]
 [ 7]
 [ 8]
 [ 3]
 [ 9]
 [ 3]
 [ 2]
 [ 1]
 [10]]
The mean of the elements of the row [ 6.  0.  7.  8.  3.  9.  3.  2.  1. 10.]
The mean of the elements of the column [4.9]


In [ ]:
#Question 3: Create a random 10 x 10 array in Python and determine the mean along the rows and columns. 
import numpy as np 
from numpy import random 
y=random.randint(100,size=(10,10)) 
print(y) 
print("The mean of the elements in the row", np.mean(y,axis=1)) #mean of rows 
print("The mean of the elements in the column", np.mean(y,axis=0)) #mean of columns

[[27 95 88 85  0 11  6 32 11 14]
 [11 46 58 15 50 98  3 14  7 10]
 [54 51 31 89 99  6 60 72  2 18]
 [62 48 53 30 36 80 76 65 83 82]
 [38 41 14 16 76 97  1 57 12 77]
 [46 43 94 12 97 42  4 78 95 40]
 [58  3  5 86 12 57 71 60 14 85]
 [13 67 76 60  1 87 83 47 60 52]
 [82 84  9 38 18 37  1 82  2 77]
 [61 76 15 47 96  5 88  8 25  9]]
The mean of the elements in the row [36.9 31.2 48.2 61.5 42.9 55.1 45.1 54.6 43.  43. ]


In [ ]:
#Question 4: Import .csv file in Python3 environment using NumPy library import numpy as np 
df=np.loadtxt('/content/NFLX.csv', delimiter=",", dtype=str) 
df=df[1:,1:] # removes first row and column 
df=df.astype('float64') #string to float 
print(df) 


[['262.000000' '267.899994' '250.029999' '254.259995' '254.259995'
  '11896100']
 ['247.699997' '266.700012' '245.000000' '265.720001' '265.720001'
  '12595800']
 ['266.579987' '272.450012' '264.329987' '264.559998' '264.559998'
  '8981500']
 ...
 ['448.250000' '451.980011' '426.480011' '429.480011' '429.480011'
  '14346000']
 ['421.440002' '429.260010' '404.279999' '405.600006' '405.600006'
  '9905200']
 ['407.309998' '412.769989' '396.640015' '410.170013' '410.170013'
  '7782400']]
